apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-dep
  template:
    metadata:
      labels:
        app: log-output-dep
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: log-output-writer
          image: pasiol/log-output-writer@sha256:82e06edab1b22c016aec7400fe1b957a8f85e4f93bcb7a98e6db4fcf98e89319
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/app/data
              name: shared-data
          env:
            - name: APP_LOG_FILE
              value: "writer.log"
            - name: APP_OUTPUT_FILE
              value: "/var/app/data/uuids.txt"
        - name: log-output-reader
          image: pasiol/log-output-reader@sha256:89ed15ba7acb7eac895958346deed05df5819f593e5e2c19126002965c75f69b
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/app/data
              name: shared-data
          env:
            - name: APP_LOG_FILE
              value: "reader.log"
            - name: APP_INPUT_FILE
              value: "/var/app/data/uuids.txt"
            - name: APP_PORT
              value: "3000"
            - name: APP_PING_PONG_HOST
              value: ping-pong-svc