apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-dep
  template:
    metadata:
      labels:
        app: log-output-dep
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: log-output-claim
        - name: reader-config
          configMap:
            name: exercise-variables
            items:
              - key: "env.properties"
                path: ".env"
      containers:
        - name: log-output-writer
          image: pasiol/log-output-writer@sha256:82e06edab1b22c016aec7400fe1b957a8f85e4f93bcb7a98e6db4fcf98e89319
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/app/data
              name: shared-data
          env:
            - name: APP_LOG_FILE
              value: "writer.log"
            - name: APP_OUTPUT_FILE
              value: "/var/app/data/uuids.txt"
        - name: log-output-reader
          image: pasiol/log-output-reader@sha256:2d67cb157ae63a24dcc697757d019317ef55d6bd8925bba58494159567021893
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/app/data
              name: shared-data
            - mountPath: /var/app
              name: reader-config
          env:
            - name: APP_LOG_FILE
              value: "reader.log"
            - name: APP_INPUT_FILE
              value: "/var/app/data/uuids.txt"
            - name: APP_PORT
              value: "3000"
            - name: APP_PING_PONG_HOST
              value: ping-pong-svc:8888