apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-hpv
  namespace: applications
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50