apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: applications
spec:
  type: NodePort
  selector:
    app: log-output-dep
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
